# Generated by Django 5.2.7 on 2025-10-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_banner_image_customuser_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='temp_profile_pictures/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='temp_banner_images/')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('verification_code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_code_expires_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_code',
        ),
    ]
