# Generated by Django 5.2.7 on 2025-10-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailverificationrequest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationRequest',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
