# Generated by Django 5.2.7 on 2025-11-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, help_text='Type of file: image, audio, video, document, or file', max_length=20, null=True),
        ),
    ]
