# Generated by Django 5.2.7 on 2025-11-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cloudinary_url',
            field=models.URLField(blank=True, help_text='URL to Cloudinary-hosted file', max_length=500, null=True),
        ),
    ]
