# Generated by Django 5.2.7 on 2025-11-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_cloudinary_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='cloudinary_url',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_type',
        ),
    ]
