# Generated by Django 5.2.7 on 2025-11-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_remove_message_cloudinary_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cloudinary_url',
            field=models.URLField(blank=True, help_text='URL to Cloudinary-hosted file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, help_text='Type of file: image, audio, video, document, or file', max_length=20, null=True),
        ),
    ]
